variables:
    IMAGE_NAME: $DOCKER_USER/vonat-web
    IMAGE_TAG: vonat_web-1.0

stages:
    - build
    - deploy

build-job:
    tags:
        - docker
    stage: build
    only:
        - main
    image: docker:24.0.6-cli
    services:
        - docker:24.0.6-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKER_USER -p "$DOCKER_PASSWORD"
        - cd src
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

deploy-job:
    tags:
        - docker
    stage: deploy
    only:
    - main
    environment: production
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 700 ~/.ssh/id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
    script:
        - ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" root@68.183.212.218
        - docker login -u $DOCKER_USER -p "$DOCKER_PASSWORD" &&
        - docker ps -aq | xargs docker stop | xargs docker rm &&
        - docker run --restart=on-failure --name vonat-web -d -p 80:3000 $IMAGE_NAME:$IMAGE_TAG
