variables:
  IMAGE_NAME: $DOCKER_USER/vonat-rf1
  IMAGE_TAG: vonat_nodejs-1.0

stages:
  - build
  - deploy

build-job:
  image: docker:24.0.6-cli
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker compose build
    - docker compose push

deploy-job:
  stage: deploy
  environment: production
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY Vonat@20.238.31.23 ""
